---
- name: install docker dependencies
  ansible.builtin.package:
    name: "{{ docker_dependencies }}"
    state: present

- name: add apt signing key (debian)
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "{{ docker_repo.gpg_url }}"
  become: true

- name: install official docker repositories for debian based
  ansible.builtin.template:
    src: etc/apt/source.list.d/docker-ce.list.j2
    dest: /etc/apt/sources.list.d/docker-ce.list
    mode: 0644
    owner: root
    group: root
