myhosts:
  vars:
    ansible_user: pejman
    ansible_port: 8090
  hosts:
    #rahbia:
    #ansible_host: 192.168.100.71
    rahbia-server-test1:
      ansible_host: 192.168.100.72
      #ansible_python_interpreter: /usr/bin/python3.12
      disk_size: 50
      datastore_name: HDD
      memory_size: 8192
      cpu_size: 2
      ip_address: 192.168.100.72
      vm_folder: RahBia-Live-Coding
      ssh_jump: ssh -W %h:%p -q labe-amoo
    rahbia-services:
      ansible_host: 192.168.100.75
      #ansible_python_interpreter: /usr/bin/python3.12
      disk_size: 100
      datastore_name: HDD
      memory_size: 8192
      cpu_size: 4
      ip_address: 192.168.100.75
      vm_folder: RahBia-Live-Coding
      ssh_jump: ssh -W %h:%p -q labe-amoo
