name: minio

networks:
  web_net:
    name: web_net
    external: true
  app_net:
    name: app_net
    external: true

volumes:
  minio_data:
    name: minio_data
    external: false
      

services:
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: minio
    hostname: minio
    restart: $ restart_policy
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: ${minio_root_user}
      MINIO_ROOT_PASSWORD: ${minio_root_password}
      MINIO_SERVER_URL: ${minio_server_url}
      MINIO_BROWSER_REDIRECT_URL: ${minio_browser_redirect_url}
      
    networks:
      - web_net
      - app_net