---
# tasks file for minio_setup
- name: Create a docker network with name
  docker_network:
    name: "{{ item }}"
    driver_options:
      com.docker.network.bridge.name: "{{ item }}"
  loop:
    - web_net
    - app_net
  tags:
    - preparing
    - docker

- name: Creates directory
  ansible.builtin.file:
    path: "{{ minio_dir }}"
    state: directory
  tags:
    - preparing
    - minio