---
- pause:
    prompt: "Do you want to delete VMs (Yes/No)?"
    echo: True
  register: confirm_delete
  run_once: True

- name: Set powerstate of virtual machine to poweroff
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    name: "{{ inventory_hostname }}"
    state: poweredoff
  delegate_to: localhost
  when: confirm_delete.user_input == 'Yes'

- name: Remove virtual machine from inventory
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    folder: "{{ vm_folder }}"
    datastore: "{{ datastore_name }}"
    validate_certs: False
    name: "{{ inventory_hostname }}"
    delete_from_inventory: True
    state: absent
  delegate_to: localhost
  when: confirm_delete.user_input == 'Yes'

- name: remove a host from the ssh configuration
  community.general.ssh_config:
    user: "{{ lookup('env','USER') }}"
    host: "{{ inventory_hostname }}"
    state: absent
  throttle: 1
  delegate_to: localhost

  when: confirm_delete.user_input == 'Yes'
