#SPDX-License-Identifier: MIT-0
---
# tasks file for vms_management
- name: setup vms
  import_tasks: create_vms.yml
  tags:
    - create_vms
    - vms_management

- name: change disk partotioning
  import_tasks: lvm_resize.yml
  tags:
    - resize_lvm
    - vms_management

- name: delete vms
  import_tasks: delete_vms.yml
  tags:
    - delete_vms
    - vms_management